version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=commerce
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./commerce.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: ngocbach99/commerce-spring:latest
    ports:
      - "8005:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
